<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome Page</title>
</head>
<body>
    <h1>User account activation page</h1>
    <h3><span style="color:green;"></span>Xush kelibsiz, ${username}</h3>
    <h4>Bizning saytdan foydalanish uchun shu <a href="http://localhost:8080/auth/user/activate?token=${token}"> Link ni bosing<a></h4>
    <img src="data:image/png; base64, %s" alt="download ">
</body>
</html>